In [1]:
from NashQLearning import *
from Environment import *

In [7]:
import pygambit as pg
import numpy as np
game = pg.Game.from_arrays(np.array([[-1,1],[-2,2]]), np.array([[1,-1],[2,-2]]))
eq = pg.nash.enummixed_solve(game).equilibria
print(eq)

[[[Rational(1, 1), Rational(0, 1)], [Rational(1, 1), Rational(0, 1)]]]


In [2]:
env = Environment()

games = env.getGames()

games[0].setPossibleActions(np.array([2, 2]))
#games[0].setPossibleActions((2, 2))
print("–––––––––––")
print(games[0])
games[0].setTransition((0, 0), 1, 1)
games[0].setPayoff((0, 0), np.array([1,1]))
print("–––––––––––")
print(games[0])
games[0].setTransition((1, 0), 0, 1)
games[0].setPayoff((1, 0), np.array([0,0]))
print("–––––––––––")
print(games[0])
games[0].setTransition((0, 1), 0, 1)
games[0].setPayoff((0, 1), np.array([0,0]))
print("–––––––––––")
print(games[0])
games[0].setTransition((1, 1), 0, 1)
games[0].setPayoff((1, 1), np.array([-1,-1]))
print("–––––––––––")
print(games[0])
###############################################

games[1].setPossibleActions(np.array([2, 2]))
#games[1].setPossibleActions((2, 2))
print("–––––––––––")
print(games[1])
games[1].setTransition((0, 0), 0, 1)
games[1].setPayoff((0, 0), np.array([1,1]))
print("–––––––––––")
print(games[1])

games[1].setTransition((1, 0), 1, 1)
games[1].setPayoff((1, 0), np.array([0,0]))
print("–––––––––––")
print(games[1])

games[1].setTransition((0, 1), 1, 1)
games[1].setPayoff((0, 1), np.array([0,0]))
print("–––––––––––")
print(games[1])

games[1].setTransition((1, 1), 1, 1)
games[1].setPayoff((1, 1), np.array([-1,-1]))
print("–––––––––––")
print(games[1])



–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{}', '{}', '{}', '{}'] 
 Payoff: [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{1: 1}', '{}', '{}', '{}'] 
 Payoff: [[[1. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{1: 1}', '{}', '{0: 1}', '{}'] 
 Payoff: [[[1. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{1: 1}', '{0: 1}', '{0: 1}', '{}'] 
 Payoff: [[[1. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{1: 1}', '{0: 1}', '{0: 1}', '{0: 1}'] 
 Payoff: [[[ 1.  1.]
  [ 0.  0.]]

 [[ 0.  0.]
  [-1. -1.]]]
–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{}', '{}', '{}', '{}'] 
 Payoff: [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
–––––––––––
Game

In [3]:
#env.getNextState(np.array([0,0]))
for game in env.getGames():
    print("–––––––––––––––––")
    print(game)

–––––––––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{1: 1}', '{0: 1}', '{0: 1}', '{0: 1}'] 
 Payoff: [[[ 1.  1.]
  [ 0.  0.]]

 [[ 0.  0.]
  [-1. -1.]]]
–––––––––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{0: 1}', '{1: 1}', '{1: 1}', '{1: 1}'] 
 Payoff: [[[ 1.  1.]
  [ 0.  0.]]

 [[ 0.  0.]
  [-1. -1.]]]


In [4]:
learn = NashQLearning(environment=env, startingState=games[0])
learn.setEpisodes(2000)
totR, diffs, Rew, H = learn.nashQlearning(0.5, 0.8, 0.1, 1500, 1500, False)

TypeError: __init__() got an unexpected keyword argument 'startingState'

In [ ]:
print(H)


In [ ]:
env = Environment(2, 3)
games = env.getGames()

games[0].setPossibleActions((2,2,2))
games[1].setPossibleActions((2,2,2))


games[0].setTransition((0, 0, 0), 0, 1)
games[0].setPayoff((0, 0, 0), np.array([-2,-2,-2]))
# print("–––––––––––")
# print(games[0])

games[0].setTransition((0, 0, 1), 0, 1)
games[0].setPayoff((0, 0, 1), np.array([-1,-1,-1]))
# print("–––––––––––")
# print(games[0])

games[0].setTransition((0, 1, 0), 0, 1)
games[0].setPayoff((0, 1, 0), np.array([-1,-1,-1]))
# print("–––––––––––")
# print(games[0])

games[0].setTransition((0, 1, 1), 0, 1)
games[0].setPayoff((0, 1, 1), np.array([0,0,0]))
# print("–––––––––––")
# print(games[0])

games[0].setTransition((1, 0, 0), 0, 1)
games[0].setPayoff((1, 0, 0), np.array([-1,-1,-1]))
# print("–––––––––––")
# print(games[0])

games[0].setTransition((1, 0, 1), 0, 1)
games[0].setPayoff((1, 0, 1), np.array([0,0,0]))
# print("–––––––––––")
# print(games[0])

games[0].setTransition((1, 1, 0), 0, 1)
games[0].setPayoff((1, 1, 0), np.array([0,0,0]))
# print("–––––––––––")
# print(games[0])

games[0].setTransition((1, 1, 1), 1, 1)
games[0].setPayoff((1, 1, 1), np.array([1,1,1]))
print("–––––––––––")
print(games[0])

"""————————————————————————————————————————————————"""

games[1].setTransition((0, 0, 0), 0, 1)
games[1].setPayoff((0, 0, 0), np.array([-2,-2,-2]))
# print("–––––––––––")
# print(games[0])

games[1].setTransition((0, 0, 1), 0, 1)
games[1].setPayoff((0, 0, 1), np.array([-1,-1,-1]))
# print("–––––––––––")
# print(games[0])

games[1].setTransition((0, 1, 0), 0, 1)
games[1].setPayoff((0, 1, 0), np.array([-1,-1,-1]))
# print("–––––––––––")
# print(games[0])

games[1].setTransition((0, 1, 1), 0, 1)
games[1].setPayoff((0, 1, 1), np.array([0,0,0]))
# print("–––––––––––")
# print(games[0])

games[1].setTransition((1, 0, 0), 0, 1)
games[1].setPayoff((1, 0, 0), np.array([-1,-1,-1]))
# print("–––––––––––")
# print(games[0])

games[1].setTransition((1, 0, 1), 0, 1)
games[1].setPayoff((1, 0, 1), np.array([0,0,0]))
# print("–––––––––––")
# print(games[0])

games[1].setTransition((1, 1, 0), 0, 1)
games[1].setPayoff((1, 1, 0), np.array([0,0,0]))
# print("–––––––––––")
# print(games[0])

games[1].setTransition((1, 1, 1), 1, 1)
games[1].setPayoff((1, 1, 1), np.array([1,1,1]))
print("–––––––––––")
print(games[1])


In [ ]:
learn = NashQLearning(environment=env, startingState=games[0])
learn.setEpisodes(2000)
totR, diffs, Rew, H = learn.nashQlearning(0.5, 0.8, 0.1, 1500, 1500, False)

In [ ]:
print(H)

In [1]:
from IPython.display import display
from NashQLearning import *
from Environment import *

In [2]:
env = Environment()

games = env.getGames()

games[0].setPossibleActions(np.array([2, 2]))
#games[0].setPossibleActions((2, 2))
print("–––––––––––")
print(games[0])
games[0].setTransition((0, 0), 1, 1)
games[0].setPayoff((0, 0), np.array([1,1]))
print("–––––––––––")
print(games[0])
games[0].setTransition((1, 0), 0, 1)
games[0].setPayoff((1, 0), np.array([0,0]))
print("–––––––––––")
print(games[0])
games[0].setTransition((0, 1), 0, 1)
games[0].setPayoff((0, 1), np.array([0,0]))
print("–––––––––––")
print(games[0])
games[0].setTransition((1, 1), 0, 1)
games[0].setPayoff((1, 1), np.array([-1,-1]))
print("–––––––––––")
print(games[0])
###############################################

games[1].setPossibleActions(np.array([2, 2]))
#games[1].setPossibleActions((2, 2))
print("–––––––––––")
print(games[1])
games[1].setTransition((0, 0), 0, 1)
games[1].setPayoff((0, 0), np.array([1,1]))
print("–––––––––––")
print(games[1])

games[1].setTransition((1, 0), 1, 1)
games[1].setPayoff((1, 0), np.array([0,0]))
print("–––––––––––")
print(games[1])

games[1].setTransition((0, 1), 1, 1)
games[1].setPayoff((0, 1), np.array([0,0]))
print("–––––––––––")
print(games[1])

games[1].setTransition((1, 1), 1, 1)
games[1].setPayoff((1, 1), np.array([-1,-1]))
print("–––––––––––")
print(games[1])



–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{}', '{}', '{}', '{}'] 
 Payoff: [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{1: 1}', '{}', '{}', '{}'] 
 Payoff: [[[1. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{1: 1}', '{}', '{0: 1}', '{}'] 
 Payoff: [[[1. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{1: 1}', '{0: 1}', '{0: 1}', '{}'] 
 Payoff: [[[1. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{1: 1}', '{0: 1}', '{0: 1}', '{0: 1}'] 
 Payoff: [[[ 1.  1.]
  [ 0.  0.]]

 [[ 0.  0.]
  [-1. -1.]]]
–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{}', '{}', '{}', '{}'] 
 Payoff: [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
–––––––––––
Game

In [3]:
learn = NashQLearning(environment=env)
display(learn.getWidget())



In [10]:
print(learn.epsilon)
print(learn.alfa)
print(learn.gamma)
print(learn.episodes)

0.1
0.5
0.9
1000


In [11]:
print(learn.history)

Q0 [[[[0.5 0.5]
   [0.  0. ]]

  [[0.  0. ]
   [0.  0. ]]]


 [[[0.  0. ]
   [0.  0. ]]

  [[0.  0. ]
   [0.  0. ]]]]
Q1 [[[[0.5 0.5]
   [0.  0. ]]

  [[0.  0. ]
   [0.  0. ]]]


 [[[0.  0. ]
   [0.  0. ]]

  [[0.  0. ]
   [0.  0. ]]]]
current_state Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{1: 1}', '{0: 1}', '{0: 1}', '{0: 1}'] 
 Payoff: [[[ 1.  1.]
  [ 0.  0.]]

 [[ 0.  0.]
  [-1. -1.]]]
1 Q0 [[[[0.5 0.5]
   [0.  0. ]]

  [[0.  0. ]
   [0.  0. ]]]


 [[[0.  0. ]
   [0.  0. ]]

  [[0.  0. ]
   [0.  0. ]]]]
Q1 [[[[0.5 0.5]
   [0.  0. ]]

  [[0.  0. ]
   [0.  0. ]]]


 [[[0.  0. ]
   [0.  0. ]]

  [[0.  0. ]
   [0.  0. ]]]]
current_state Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{1: 1}', '{0: 1}', '{0: 1}', '{0: 1}'] 
 Payoff: [[[ 1.  1.]
  [ 0.  0.]]

 [[ 0.  0.]
  [-1. -1.]]]
Q0: [[[[0.5 0.5]
   [0.  0. ]]

  [[0.  0. ]
   [0.  0. ]]]


 [[[0.  0. ]
   [0.  0. ]]

  [[0.  0. ]
   [0.  0. ]]]]
Q1: [[[[0.5 0.5]
   [0.  0. ]]

  [[0.  0. 