In [1]:
from NashQLearning import *
from Environment import *

In [2]:
env = Environment()

games = env.getGames()

games[0].setPossibleActions(np.array([2, 2]))
#games[0].setPossibleActions((2, 2))
print("–––––––––––")
print(games[0])
games[0].setTransition((0, 0), 1, 1)
games[0].setPayoff((0, 0), np.array([1,1]))
print("–––––––––––")
print(games[0])
games[0].setTransition((1, 0), 0, 1)
games[0].setPayoff((1, 0), np.array([0,0]))
print("–––––––––––")
print(games[0])
games[0].setTransition((0, 1), 0, 1)
games[0].setPayoff((0, 1), np.array([0,0]))
print("–––––––––––")
print(games[0])
games[0].setTransition((1, 1), 0, 1)
games[0].setPayoff((1, 1), np.array([-1,-1]))
print("–––––––––––")
print(games[0])
###############################################

games[1].setPossibleActions(np.array([2, 2]))
#games[1].setPossibleActions((2, 2))
print("–––––––––––")
print(games[1])
games[1].setTransition((0, 0), 0, 1)
games[1].setPayoff((0, 0), np.array([1,1]))
print("–––––––––––")
print(games[1])

games[1].setTransition((1, 0), 1, 1)
games[1].setPayoff((1, 0), np.array([0,0]))
print("–––––––––––")
print(games[1])

games[1].setTransition((0, 1), 1, 1)
games[1].setPayoff((0, 1), np.array([0,0]))
print("–––––––––––")
print(games[1])

games[1].setTransition((1, 1), 1, 1)
games[1].setPayoff((1, 1), np.array([-1,-1]))
print("–––––––––––")
print(games[1])



–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{}', '{}', '{}', '{}'] 
 Payoff: [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{1: 1}', '{}', '{}', '{}'] 
 Payoff: [[[1. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{1: 1}', '{}', '{0: 1}', '{}'] 
 Payoff: [[[1. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{1: 1}', '{0: 1}', '{0: 1}', '{}'] 
 Payoff: [[[1. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{1: 1}', '{0: 1}', '{0: 1}', '{0: 1}'] 
 Payoff: [[[ 1.  1.]
  [ 0.  0.]]

 [[ 0.  0.]
  [-1. -1.]]]
–––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{}', '{}', '{}', '{}'] 
 Payoff: [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
–––––––––––
Game

In [3]:
#env.getNextState(np.array([0,0]))
for game in env.getGames():
    print("–––––––––––––––––")
    print(game)

–––––––––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{1: 1}', '{0: 1}', '{0: 1}', '{0: 1}'] 
 Payoff: [[[ 1.  1.]
  [ 0.  0.]]

 [[ 0.  0.]
  [-1. -1.]]]
–––––––––––––––––
Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{0: 1}', '{1: 1}', '{1: 1}', '{1: 1}'] 
 Payoff: [[[ 1.  1.]
  [ 0.  0.]]

 [[ 0.  0.]
  [-1. -1.]]]


In [6]:
learn = NashQLearning(environment=env, startingState=games[0])
learn.setEpisodes(2000)
totR, diffs, Rew, H = learn.nashQlearning(0.5, 0.8, 0.1, 1500, 1500, False)

IntProgress(value=0, bar_style='info', description='Games:', max=0)

In [7]:
print(H)


Q0 [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
Q1 [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
current_state Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{0: 1}', '{1: 1}', '{1: 1}', '{1: 1}'] 
 Payoff: [[[ 1.  1.]
  [ 0.  0.]]

 [[ 0.  0.]
  [-1. -1.]]]
0 Q0 [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
Q1 [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
current_state Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{0: 1}', '{1: 1}', '{1: 1}', '{1: 1}'] 
 Payoff: [[[ 1.  1.]
  [ 0.  0.]]

 [[ 0.  0.]
  [-1. -1.]]]
Q0: [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
Q1: [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
current_state: Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Transition: ['{0: 1}', '{1: 1}', '{1: 1}', '{1: 1}'] 
 Payoff: [[[ 1.  1.]
  [ 0.  0.]]

 [[ 0.  0.]
  [-1. -1.]]]

Q0 [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
Q1 [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
current_state Game: [2 2] 
 PossibileActions:[2 2] 
 NPlayers: 2 
 Trans