In [1]:
import ipywidgets as widgets
from IPython.display import display
import numpy as np

In [2]:
from Classes.PlayerSelection import PlayerSelection

In [3]:
playerSelection = PlayerSelection([2, 2])
display(playerSelection.getWidget())

In [4]:
TRANSITION_MATRIX = np.array(
    [
        # Player 1 - Action 0
        [
            # Player 2 - Action 0 - .1 .3
            [
                
                [0, 0.5, 0, 0.5],
                [0, 1, 0, 0],
                [0, 0, 1, 0],
                [0.5, 0, 0, 0.5]
                
            ],

            # Player 2 - Action 1 .2 .3
            [
                
                [1, 0, 0, 0],
                [0, 0, 1, 0],
                [0, 0, 0, 1],
                [0.5, 0, 0, 0.5]
                
            ]
        ],

        # Player 1 - Action 1
        [
            # Player 2 - Action 0 .1 .4
            [
                
                [1, 0, 0, 0],
                [0, 0, 0, 1],
                [0, 0, 0, 1],
                [0.5, 0, 0, 0.5]
                
            ],

            # Player 2 - Action 1 .2 .4
            [
                
                [0, 0.5, 0, 0.5],
                [0, 0, 1, 0],
                [0, 0, 0, 1],
                [0.5, 0, 0, 0.5]
                
            ]
        ]
    ]
)

In [5]:
TRANSITION_MATRIX.shape

(2, 2, 4, 4)

In [6]:
TRANSITION_MATRIX.reshape(-1, 4, 4).shape
Q = 4

In [7]:
nPlayers = playerSelection.getNPlayers()
actions = np.prod(playerSelection.getData())
linearShape = (actions,) + (Q,) * nPlayers
linearShape

(4, 4, 4)

In [8]:
from Classes.TransitionSelection import TransitionSelection

In [9]:
transitionSelection = TransitionSelection(TRANSITION_MATRIX, playerSelection, Q)

In [10]:
display(transitionSelection.getWidget())

In [11]:
print(transitionSelection.getData())

[[[[0.  0.5 0.  0.5]
   [0.  1.  0.  0. ]
   [0.  0.  1.  0. ]
   [0.5 0.  0.  0.5]]

  [[1.  0.  0.  0. ]
   [0.  0.  1.  0. ]
   [0.  0.  0.  1. ]
   [0.5 0.  0.  0.5]]]


 [[[1.  0.  0.  0. ]
   [0.  0.  0.  1. ]
   [0.  0.  0.  1. ]
   [0.5 0.  0.  0.5]]

  [[0.  0.5 0.  0.5]
   [0.  0.  1.  0. ]
   [0.  0.  0.  1. ]
   [0.5 0.  0.  0.5]]]]


In [12]:
from Classes.PayoffSelection import PayoffSelection

In [13]:
# state / player1 action / player2 action / [player1 reward, player2 reward]
PAYOFF_MATRIX = np.array([
    # State 0
    [
        [ [2, 1], [0, 0] ],
        [ [0, 0], [1, 2] ]
    ],
    # State 1
    [
        [ [1, 1], [3, 0] ],
        [ [0, 3], [2, 2] ]
    ],
    # State 
    [
        [ [2, 0], [0, 2] ],
        [ [0, 1], [1, 0] ]
    ],
    # State 33
    [
        [ [1, 1], [0, 0] ],
        [ [0, 0], [2, 2] ]
    ],
], dtype=object)

In [14]:
payoffSelection = PayoffSelection(PAYOFF_MATRIX, playerSelection)

In [15]:
display(payoffSelection.getWidget())